name: ci

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps: 
      - name: Chekckout repository
        uses: actions/checkout@v2
        with:
          fecth-depth: 0
          
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ^14.15.0
      
      - uses: actions/cache@v2
        id: yarn-cache
        with: 
          path: '**/node_modules'
          key: ${{ runner.os}}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependecies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        
      - name: Run Jest tests
        run: yarn test

      - name: Falhar de proposito
        run: yarn test
      
      - name: Run Linter
        run: yarn lint
        

      - name: Notify in telegran - success
        uses: appleboy/telegram-action@master
        if: ${{ success()}}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            After ${{ github.event_name }} the deploy was done at Netlify!

      - name: Notify in telegran - error
        uses: appleboy/telegram-action@master
        if: ${{ failure()}}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            After ${{ github.event_name }} the deploy at Netlify failed!
