name: ci

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps: 
      - name: Chekckout repository
        uses: actions/checkout@v2
        with:
          fecth-depth: 0
          
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ^14.15.0
      
      - name: Install dependecies
        run: yarn --frozen-lockfile
        
      - name: Run Jest tests
        run: yarn test
      
      - name: Run Linter
        run: yarn lint
        

      - name: send message using socks5 proxy URL
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed